// `AppConfig` mirrors the Rust model (generated by ts-rs, `pnpm gen:types`),
// with literal unions hand-narrowed for the fields the backend validates
// (`hotCorner` / `theme`) so the settings UI keeps compile-time narrowing.
import type { AppConfig as GeneratedAppConfig } from "./generated/AppConfig";

export type { QuietHours } from "./generated/QuietHours";
import type { QuietHours } from "./generated/QuietHours";

export type AppConfig = Omit<GeneratedAppConfig, "hotCorner" | "theme" | "quietHours"> & {
  hotCorner: "off" | "top-left" | "top-right" | "bottom-left" | "bottom-right";
  theme: "system" | "dark" | "light";
  /** Optional quiet window for due reminders; `null` keeps reminders always on. */
  quietHours: QuietHours | null;
};
