// Mirrors Rust `models::github`, `services::github` sync types and the
// `commands::github` results, generated by ts-rs (`pnpm gen:types`).
export type { GhAuthStatus } from "./generated/GhAuthStatus";
export type { ActionSignal } from "./generated/ActionSignal";
export type { GhIgnoredItem } from "./generated/GhIgnoredItem";
export type { RepoWatch } from "./generated/RepoWatch";
export type { GhIssue } from "./generated/GhIssue";
export type { GhPullRequest } from "./generated/GhPullRequest";
export type { RepoSnapshot } from "./generated/RepoSnapshot";
export type { GithubSyncFailure } from "./generated/GithubSyncFailure";
export type { GithubSyncSummary } from "./generated/GithubSyncSummary";
export type { GithubRefreshResult } from "./generated/GithubRefreshResult";
export type { GithubRefreshAllResult } from "./generated/GithubRefreshAllResult";
export type { GithubOverview } from "./generated/GithubOverview";
