// Mirrors Rust `models::note`, generated by ts-rs (`pnpm gen:types`).
import type { Note } from "./generated/Note";

export type { WindowBounds } from "./generated/WindowBounds";
export type { Note } from "./generated/Note";

export type NotePatch = Partial<Omit<Note, "id" | "schemaVersion" | "createdAt" | "updatedAt">>;
